title: Adel Marzban | Tissue Banking Innovation & Biomedical AI | عادل مرزبان
email: adelmarzban@gmail.com
description: >-
  Advancing Medicine Through Tissue Innovation, Data Science, and Digital Health.
baseurl: ""
url: "https://adelmarzban.github.io"
google_site_verification: "1YXxtaPSg2KsLAHGV5mAy8dvOUalsuZk9u0bES2TvpI"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap   # ✅ allowed on GitHub Pages
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme


permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"


collections:
  publications:
    output: true
    permalink: /publications/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"   # _layouts/publication.html

# show in Minima’s top nav if you want
header_pages:
  - publications.html
  - blog.html
  - contact.md

# optional: include publications in your RSS feed
feed:
  collections:
    - publications
